org.gradle.jvmargs=-Xmx8G

# Project Properties
mod_id=mavm
mod_name=More Axolotl Variants Mod
mod_author=AkashiiKun
mod_description=Adds more axolotl variants!
discord=https://discord.gg/NvwhXq493P
source=https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common
mod_version=1.3.1
mod_license=ARR
maven_group=io.github.akashiikun

enabled_platforms=fabric

minecraft=1.21.1
fabric_loader=0.17.2
fabric_api=0.116.6
neoforge_version=20.6.11-beta
neoforge_compat=20.6-beta
neoforge_loader=3

mavapi_version=1.3.0
modmenu_version=11.0.3
sodium_version=0.6.9