modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="All Rights Reserved"
[[mods]]
modId="mavm-bp" #mandatory
version="${file.jarVersion}"
displayName="More Axolotl Variants Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mavm-bp"
logoFile="logo.png"
authors="Akashii_Kun"
description='''Adds more axolotl variants!'''

[[dependencies.mavm]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.mavm]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5]"
   ordering="NONE"
   side="BOTH"

# Caves & Cliffs Backport
[[dependencies.mavm]]
   modId="cavesandcliffs"
   mandatory=true
   versionRange="[1.16.5-7.2.0]"
   ordering="NONE"
   side="BOTH"
